apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyGateway
metadata:
  name: envoy-gateway
  namespace: envoy-gateway-system
spec:
  gateway:
    controllerName: gateway.envoyproxy.io/gatewayclass-controller
  provider:
    type: Kubernetes
  logging:
    level:
      default: info
  extensionApis:
    enable: true
  rateLimit:
    backend:
      type: Redis
      redis:
        url: redis-service.envoy-gateway-system:6379
  extensionServer:
    port: 8080
    host: 0.0.0.0
  extensionFilters:
    - name: bedrock
      type: HTTP
      config:
        region: ${BEDROCK_REGION}
        assumeRoleArn: ${BEDROCK_ASSUME_ROLE_ARN}
        models:
          - name: claude
            modelId: anthropic.claude-v2
            routePrefix: /claude
          - name: llama
            modelId: meta.llama2-13b-chat-v1
            routePrefix: /llama 